### ISSUE TITLE
[Enhancement]: Changing the height of the card

### ISSUE THREAD

**Issue by DaN66O** [francois-le-ko4la/lovelace-entity-progress-card#64]
### Requirements

- [x] I checked the README.
- [x] I have updated entity-progress-card to the latest available version.
- [x] I did a search to see if there is a similar issue.

### What would you like to improve?

I'm trying to change the height of the card with styles
```
    card_mod:
      style: |
        ha-card {
          height: 36px !important;
        }
```
And nothing happens.
Is it possible to add an option to change the height, or can you tell me how to do it with styles?
`min-height: 56px; `does not allow you to change the height.

### Why is this improvement helpful?

When you combine several lovelace-entity-progress-cards into one card, I would like to group them more often.

**Comment by DaN66O** [comment]
I kind of figure out what the reason was.
I use your card in conjunction with layout-card
( https://github.com/thomasloven/lovelace-layout-card )
layout-card does not allow you to change the height.
The height changes without using the layout-card.
I'll figure out why.

**Comment by francois-le-ko4la** [comment]
No worry. I will also take a look.
I think, I have frameless to avoid border but I can also create a parameter to remove the margin....
I will test it.

**Comment by francois-le-ko4la** [comment]
hello @DaN66O,

The challenge came from the fact that the 'container' div was fixed at a minimum of 56px.
With the new 'marginless' option, I’m disabling that behavior, which should allow you to do what you want.
It will be available in the next release.

TY.

**Comment by DaN66O** [comment]
> Это будет доступно в следующем выпуске.

Thanks 
I look forward to

**Comment by DaN66O** [comment]
> Whenever you have a moment, please test it and let me know if everything looks good on your end.

That's right
**marginless** removes vertical margin, creating a more compact layout.
But the height change styles still don't work, and I can't set an arbitrary value.
```
    card_mod: 
      style: |
        ha-card {
          height: 26px !important;
        }
```
It doesn't work.

**Comment by francois-le-ko4la** [comment]
hello @DaN66O

If its not a fixed value, it will be difficult to do something that will fit everytime ^^
In the other hand, condition with this card and for other layout can change a lot......
ok so I continue to think marginless is usefull, because simple to push, and the heigh parameter MUST be available on my card.

I like card mod but yes a simple parameter can help a lot and simplify this kind of setup.

next release:
- marginless optimization
- height parameter:
![Image](https://github.com/user-attachments/assets/485e4ac4-f76c-40ad-b38b-f0a9a44e146c)

TY.

**Comment by DaN66O** [comment]
It turned out great !!!

**Comment by francois-le-ko4la** [comment]
I like the look & feel.....
Really nice.

Thx a lot for your feedback.
